### ISSUE TITLE
The creator of LateNight might DMCA the repo

### ISSUE THREAD

**Issue by Ali00035v2** [LateNight-Archived/LATENIGHT-ARCHIVED-#1]
In-case of that happening, download the repo for re-uploading.

Forking is useless most of the time as you can DMCA the forks too.

**Comment by LateNight-Archived** [comment]
yea, if you notice the zip file is the original repo.
I have multiple backups
dw <3

> In-case of that happening, download the repo for re-uploading.
> 
> Forking is useless most of the time as you can DMCA the forks too.

**Comment by Ali00035v2** [comment]
> yea, if you notice the zip file is the original repo. I have multiple backups dw <3
> 
> > In-case of that happening, download the repo for re-uploading.
> > Forking is useless most of the time as you can DMCA the forks too.

:D
